config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders do
    resources :order_items
  end
  resources :products
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name,  presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%#= form_with(model: category, local: true, class: "card p-4 shadow") do |form| %>
  <%# if category.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>-->

<!--      <ul>-->
        <%# category.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div>-->
    <%#= form.label :name, style: "display: block" %>
    <%#= form.text_field :name %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>



<%= form_with(model: category, local: true, class: "card p-4 shadow") do |form| %>
  <div class="mb-3">
    <%= form.label :name, "Название", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

<!--  <div class="mb-3">-->
    <%#= form.label :email, "Email", class: "form-label" %>
    <%#= form.email_field :email, class: "form-control" %>
<!--  </div>-->

  <div class="text-end">
    <%= form.submit "Сохранить", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category, class: "btn btn-info btn-sm" %> |
  <%= link_to "Back to categories", categories_path, class: "btn btn-secondary btn-sm" %>
</div>

app/views/categories/index.html.erb
<h1 class="mb-4">Категории</h1>

<table class="table table-striped table-bordered">
  <thead class="table-dark">
  <tr>
    <th>Название</th>
    <th>Действия</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td>
        <%= link_to "Показать", category_path(category), class: "btn btn-info btn-sm" %>
        <%= link_to "Редактировать", edit_category_path(category), class: "btn btn-warning btn-sm" %>
        <%= link_to "Удалить", category_path(category), method: :delete, data: { confirm: "Вы уверены?" }, class: "btn btn-danger btn-sm" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "Добавить категорию", new_category_path, class: "btn btn-success" %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<% content_for :title, "Show category" %>

<p style="color: green"><%= notice %></p>

<%#= render @category %>

<div class="card p-4 shadow">
  <p><strong>Название категории:</strong> <%= @category.name %></p>
</div>

<br>

<div>
  <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-warning btn-sm"%> |
  <%= link_to "Delete this category", @category, method: :delete, data: { confirm: "Вы уверены?" }, class: "btn btn-danger btn-sm"%> |
  <%= link_to "Back to categories", categories_path, class: "btn btn-secondary btn-sm" %>
</div>