config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :orders do
    resources :order_items
  end
  resources :products
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Testruby" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
    <%= javascript_include_tag "rails-ujs", "data-turbo-track": "reload" %>


  </head>

  <body class="bg-light">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to "home", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Переключить навигацию">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Пользователи", users_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Категории", categories_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Товары", products_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Заказы", orders_path, class: "nav-link" %></li>
        </ul>

        <ul class="navbar-nav ms-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
            <span class="navbar-text nav-link">
              Добро пожаловать, <%= current_user.name %>!
            </span>
            </li>
            <li class="nav-item">
              <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Войти', new_user_session_path, class: 'btn btn-outline-primary' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn btn-outline-success' %>
            </li>
          <% end %>
        </ul>

      </div>


      <%# if user_signed_in? %>
<!--        <p>Добро пожаловать, <%#= current_user.name %>!</p>-->
        <%#= link_to "Выйти", destroy_user_session_path, method: :delete %>
      <%# else %>
        <%#= link_to "Войти", new_user_session_path %>
        <%#= link_to "Зарегистрироваться", new_user_registration_path %>
      <%# end %>

      <%#= link_to 'Выйти', destroy_user_session_path, method: :delete %>


    </div>
  </nav>

  <div class="container mt-4">

    <%#= render "shared/_error_messages" %>
    <%= yield %>
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>